### ISSUE TITLE
Ability to define aspect ratio with aspect ratio format: ratio="16:9"

### ISSUE THREAD

**Issue by paales** [diddledan/proportional-height-box#1]
```html
<proportional-height-box ratio="16:9"></proportional-height-box>
```

**Comment by lucyllewy** [comment]
Do you have a use-case where the ratio is easier to not be split into separate parts and put in the width and height fields? The width and height fields serve the purpose of building the ratio currently so you can use `16` and `9` as their vales:

```
<proportional-height-box width="16" height="19"></proportional-height-box>
```

**Comment by paales** [comment]
Well, maybe the documentation should just say more logical aspect ratio numbers, instead of the 200 / 300 currently used. :)

In our own application we'd specify the width as one and the height as a ratio of the height, so that becomes: width:1, height:1.43.

Ps. Thanks for making the component, I like the 'shareability' of the webcomponents.
Ps 2. You might want to include the keywords Aspect Ratio in your readme, couldn't find it easily on webcomponents.org.

**Comment by lucyllewy** [comment]
I've added a small blurb about aspect ratio being acceptable in the README.md. I'm not completely against adding the `ratio` attribute but at the moment feel that `width` and `height` can be sufficient.

I've also updated bower.json to include `aspect ratio` as a keyword.

**Comment by paales** [comment]
@diddledan Looks great 👍

**Comment by lucyllewy** [comment]
Thanks for helping out :-) I'm always open to suggestions if you find anything that I can improve.
